/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as WorkspaceRouteImport } from './routes/$workspace'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceIndexRouteImport } from './routes/$workspace/index'
import { Route as WorkspaceTeamRouteImport } from './routes/$workspace/team'
import { Route as WorkspaceTasksRouteImport } from './routes/$workspace/tasks'
import { Route as WorkspaceSettingsRouteImport } from './routes/$workspace/settings'
import { Route as WorkspaceSalesRouteImport } from './routes/$workspace/sales'
import { Route as WorkspacePrRouteImport } from './routes/$workspace/pr'
import { Route as WorkspacePmTasksRouteImport } from './routes/$workspace/pm-tasks'
import { Route as WorkspaceLogisticsRouteImport } from './routes/$workspace/logistics'
import { Route as WorkspaceDxpRouteImport } from './routes/$workspace/dxp'
import { Route as WorkspaceCalendarRouteImport } from './routes/$workspace/calendar'
import { Route as WorkspaceActivityRouteImport } from './routes/$workspace/activity'
import { Route as WorkspaceDxpIndexRouteImport } from './routes/$workspace/dxp/index'
import { Route as WorkspaceDxpWhatsappRouteImport } from './routes/$workspace/dxp/whatsapp'
import { Route as WorkspaceDxpPhysicalRouteImport } from './routes/$workspace/dxp/physical'
import { Route as WorkspaceDxpOne2oneRouteImport } from './routes/$workspace/dxp/one2one'
import { Route as WorkspaceDxpEmailRouteImport } from './routes/$workspace/dxp/email'
import { Route as WorkspaceDxpDdayRouteImport } from './routes/$workspace/dxp/dday'
import { Route as WorkspaceDxpAgendaRouteImport } from './routes/$workspace/dxp/agenda'

const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/$workspace',
  path: '/$workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTeamRoute = WorkspaceTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceTasksRoute = WorkspaceTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceSalesRoute = WorkspaceSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePrRoute = WorkspacePrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspacePmTasksRoute = WorkspacePmTasksRouteImport.update({
  id: '/pm-tasks',
  path: '/pm-tasks',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceLogisticsRoute = WorkspaceLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDxpRoute = WorkspaceDxpRouteImport.update({
  id: '/dxp',
  path: '/dxp',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceCalendarRoute = WorkspaceCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceActivityRoute = WorkspaceActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceDxpIndexRoute = WorkspaceDxpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceDxpRoute,
} as any)
const WorkspaceDxpWhatsappRoute = WorkspaceDxpWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => WorkspaceDxpRoute,
} as any)
const WorkspaceDxpPhysicalRoute = WorkspaceDxpPhysicalRouteImport.update({
  id: '/physical',
  path: '/physical',
  getParentRoute: () => WorkspaceDxpRoute,
} as any)
const WorkspaceDxpOne2oneRoute = WorkspaceDxpOne2oneRouteImport.update({
  id: '/one2one',
  path: '/one2one',
  getParentRoute: () => WorkspaceDxpRoute,
} as any)
const WorkspaceDxpEmailRoute = WorkspaceDxpEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => WorkspaceDxpRoute,
} as any)
const WorkspaceDxpDdayRoute = WorkspaceDxpDdayRouteImport.update({
  id: '/dday',
  path: '/dday',
  getParentRoute: () => WorkspaceDxpRoute,
} as any)
const WorkspaceDxpAgendaRoute = WorkspaceDxpAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => WorkspaceDxpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
  '/$workspace/activity': typeof WorkspaceActivityRoute
  '/$workspace/calendar': typeof WorkspaceCalendarRoute
  '/$workspace/dxp': typeof WorkspaceDxpRouteWithChildren
  '/$workspace/logistics': typeof WorkspaceLogisticsRoute
  '/$workspace/pm-tasks': typeof WorkspacePmTasksRoute
  '/$workspace/pr': typeof WorkspacePrRoute
  '/$workspace/sales': typeof WorkspaceSalesRoute
  '/$workspace/settings': typeof WorkspaceSettingsRoute
  '/$workspace/tasks': typeof WorkspaceTasksRoute
  '/$workspace/team': typeof WorkspaceTeamRoute
  '/$workspace/': typeof WorkspaceIndexRoute
  '/$workspace/dxp/agenda': typeof WorkspaceDxpAgendaRoute
  '/$workspace/dxp/dday': typeof WorkspaceDxpDdayRoute
  '/$workspace/dxp/email': typeof WorkspaceDxpEmailRoute
  '/$workspace/dxp/one2one': typeof WorkspaceDxpOne2oneRoute
  '/$workspace/dxp/physical': typeof WorkspaceDxpPhysicalRoute
  '/$workspace/dxp/whatsapp': typeof WorkspaceDxpWhatsappRoute
  '/$workspace/dxp/': typeof WorkspaceDxpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
  '/$workspace/activity': typeof WorkspaceActivityRoute
  '/$workspace/calendar': typeof WorkspaceCalendarRoute
  '/$workspace/logistics': typeof WorkspaceLogisticsRoute
  '/$workspace/pm-tasks': typeof WorkspacePmTasksRoute
  '/$workspace/pr': typeof WorkspacePrRoute
  '/$workspace/sales': typeof WorkspaceSalesRoute
  '/$workspace/settings': typeof WorkspaceSettingsRoute
  '/$workspace/tasks': typeof WorkspaceTasksRoute
  '/$workspace/team': typeof WorkspaceTeamRoute
  '/$workspace': typeof WorkspaceIndexRoute
  '/$workspace/dxp/agenda': typeof WorkspaceDxpAgendaRoute
  '/$workspace/dxp/dday': typeof WorkspaceDxpDdayRoute
  '/$workspace/dxp/email': typeof WorkspaceDxpEmailRoute
  '/$workspace/dxp/one2one': typeof WorkspaceDxpOne2oneRoute
  '/$workspace/dxp/physical': typeof WorkspaceDxpPhysicalRoute
  '/$workspace/dxp/whatsapp': typeof WorkspaceDxpWhatsappRoute
  '/$workspace/dxp': typeof WorkspaceDxpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspace': typeof WorkspaceRouteWithChildren
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/sales': typeof SalesRoute
  '/$workspace/activity': typeof WorkspaceActivityRoute
  '/$workspace/calendar': typeof WorkspaceCalendarRoute
  '/$workspace/dxp': typeof WorkspaceDxpRouteWithChildren
  '/$workspace/logistics': typeof WorkspaceLogisticsRoute
  '/$workspace/pm-tasks': typeof WorkspacePmTasksRoute
  '/$workspace/pr': typeof WorkspacePrRoute
  '/$workspace/sales': typeof WorkspaceSalesRoute
  '/$workspace/settings': typeof WorkspaceSettingsRoute
  '/$workspace/tasks': typeof WorkspaceTasksRoute
  '/$workspace/team': typeof WorkspaceTeamRoute
  '/$workspace/': typeof WorkspaceIndexRoute
  '/$workspace/dxp/agenda': typeof WorkspaceDxpAgendaRoute
  '/$workspace/dxp/dday': typeof WorkspaceDxpDdayRoute
  '/$workspace/dxp/email': typeof WorkspaceDxpEmailRoute
  '/$workspace/dxp/one2one': typeof WorkspaceDxpOne2oneRoute
  '/$workspace/dxp/physical': typeof WorkspaceDxpPhysicalRoute
  '/$workspace/dxp/whatsapp': typeof WorkspaceDxpWhatsappRoute
  '/$workspace/dxp/': typeof WorkspaceDxpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspace'
    | '/admin'
    | '/login'
    | '/sales'
    | '/$workspace/activity'
    | '/$workspace/calendar'
    | '/$workspace/dxp'
    | '/$workspace/logistics'
    | '/$workspace/pm-tasks'
    | '/$workspace/pr'
    | '/$workspace/sales'
    | '/$workspace/settings'
    | '/$workspace/tasks'
    | '/$workspace/team'
    | '/$workspace/'
    | '/$workspace/dxp/agenda'
    | '/$workspace/dxp/dday'
    | '/$workspace/dxp/email'
    | '/$workspace/dxp/one2one'
    | '/$workspace/dxp/physical'
    | '/$workspace/dxp/whatsapp'
    | '/$workspace/dxp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/sales'
    | '/$workspace/activity'
    | '/$workspace/calendar'
    | '/$workspace/logistics'
    | '/$workspace/pm-tasks'
    | '/$workspace/pr'
    | '/$workspace/sales'
    | '/$workspace/settings'
    | '/$workspace/tasks'
    | '/$workspace/team'
    | '/$workspace'
    | '/$workspace/dxp/agenda'
    | '/$workspace/dxp/dday'
    | '/$workspace/dxp/email'
    | '/$workspace/dxp/one2one'
    | '/$workspace/dxp/physical'
    | '/$workspace/dxp/whatsapp'
    | '/$workspace/dxp'
  id:
    | '__root__'
    | '/'
    | '/$workspace'
    | '/admin'
    | '/login'
    | '/sales'
    | '/$workspace/activity'
    | '/$workspace/calendar'
    | '/$workspace/dxp'
    | '/$workspace/logistics'
    | '/$workspace/pm-tasks'
    | '/$workspace/pr'
    | '/$workspace/sales'
    | '/$workspace/settings'
    | '/$workspace/tasks'
    | '/$workspace/team'
    | '/$workspace/'
    | '/$workspace/dxp/agenda'
    | '/$workspace/dxp/dday'
    | '/$workspace/dxp/email'
    | '/$workspace/dxp/one2one'
    | '/$workspace/dxp/physical'
    | '/$workspace/dxp/whatsapp'
    | '/$workspace/dxp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SalesRoute: typeof SalesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace': {
      id: '/$workspace'
      path: '/$workspace'
      fullPath: '/$workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspace/': {
      id: '/$workspace/'
      path: '/'
      fullPath: '/$workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/team': {
      id: '/$workspace/team'
      path: '/team'
      fullPath: '/$workspace/team'
      preLoaderRoute: typeof WorkspaceTeamRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/tasks': {
      id: '/$workspace/tasks'
      path: '/tasks'
      fullPath: '/$workspace/tasks'
      preLoaderRoute: typeof WorkspaceTasksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/settings': {
      id: '/$workspace/settings'
      path: '/settings'
      fullPath: '/$workspace/settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/sales': {
      id: '/$workspace/sales'
      path: '/sales'
      fullPath: '/$workspace/sales'
      preLoaderRoute: typeof WorkspaceSalesRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/pr': {
      id: '/$workspace/pr'
      path: '/pr'
      fullPath: '/$workspace/pr'
      preLoaderRoute: typeof WorkspacePrRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/pm-tasks': {
      id: '/$workspace/pm-tasks'
      path: '/pm-tasks'
      fullPath: '/$workspace/pm-tasks'
      preLoaderRoute: typeof WorkspacePmTasksRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/logistics': {
      id: '/$workspace/logistics'
      path: '/logistics'
      fullPath: '/$workspace/logistics'
      preLoaderRoute: typeof WorkspaceLogisticsRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/dxp': {
      id: '/$workspace/dxp'
      path: '/dxp'
      fullPath: '/$workspace/dxp'
      preLoaderRoute: typeof WorkspaceDxpRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/calendar': {
      id: '/$workspace/calendar'
      path: '/calendar'
      fullPath: '/$workspace/calendar'
      preLoaderRoute: typeof WorkspaceCalendarRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/activity': {
      id: '/$workspace/activity'
      path: '/activity'
      fullPath: '/$workspace/activity'
      preLoaderRoute: typeof WorkspaceActivityRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/$workspace/dxp/': {
      id: '/$workspace/dxp/'
      path: '/'
      fullPath: '/$workspace/dxp/'
      preLoaderRoute: typeof WorkspaceDxpIndexRouteImport
      parentRoute: typeof WorkspaceDxpRoute
    }
    '/$workspace/dxp/whatsapp': {
      id: '/$workspace/dxp/whatsapp'
      path: '/whatsapp'
      fullPath: '/$workspace/dxp/whatsapp'
      preLoaderRoute: typeof WorkspaceDxpWhatsappRouteImport
      parentRoute: typeof WorkspaceDxpRoute
    }
    '/$workspace/dxp/physical': {
      id: '/$workspace/dxp/physical'
      path: '/physical'
      fullPath: '/$workspace/dxp/physical'
      preLoaderRoute: typeof WorkspaceDxpPhysicalRouteImport
      parentRoute: typeof WorkspaceDxpRoute
    }
    '/$workspace/dxp/one2one': {
      id: '/$workspace/dxp/one2one'
      path: '/one2one'
      fullPath: '/$workspace/dxp/one2one'
      preLoaderRoute: typeof WorkspaceDxpOne2oneRouteImport
      parentRoute: typeof WorkspaceDxpRoute
    }
    '/$workspace/dxp/email': {
      id: '/$workspace/dxp/email'
      path: '/email'
      fullPath: '/$workspace/dxp/email'
      preLoaderRoute: typeof WorkspaceDxpEmailRouteImport
      parentRoute: typeof WorkspaceDxpRoute
    }
    '/$workspace/dxp/dday': {
      id: '/$workspace/dxp/dday'
      path: '/dday'
      fullPath: '/$workspace/dxp/dday'
      preLoaderRoute: typeof WorkspaceDxpDdayRouteImport
      parentRoute: typeof WorkspaceDxpRoute
    }
    '/$workspace/dxp/agenda': {
      id: '/$workspace/dxp/agenda'
      path: '/agenda'
      fullPath: '/$workspace/dxp/agenda'
      preLoaderRoute: typeof WorkspaceDxpAgendaRouteImport
      parentRoute: typeof WorkspaceDxpRoute
    }
  }
}

interface WorkspaceDxpRouteChildren {
  WorkspaceDxpAgendaRoute: typeof WorkspaceDxpAgendaRoute
  WorkspaceDxpDdayRoute: typeof WorkspaceDxpDdayRoute
  WorkspaceDxpEmailRoute: typeof WorkspaceDxpEmailRoute
  WorkspaceDxpOne2oneRoute: typeof WorkspaceDxpOne2oneRoute
  WorkspaceDxpPhysicalRoute: typeof WorkspaceDxpPhysicalRoute
  WorkspaceDxpWhatsappRoute: typeof WorkspaceDxpWhatsappRoute
  WorkspaceDxpIndexRoute: typeof WorkspaceDxpIndexRoute
}

const WorkspaceDxpRouteChildren: WorkspaceDxpRouteChildren = {
  WorkspaceDxpAgendaRoute: WorkspaceDxpAgendaRoute,
  WorkspaceDxpDdayRoute: WorkspaceDxpDdayRoute,
  WorkspaceDxpEmailRoute: WorkspaceDxpEmailRoute,
  WorkspaceDxpOne2oneRoute: WorkspaceDxpOne2oneRoute,
  WorkspaceDxpPhysicalRoute: WorkspaceDxpPhysicalRoute,
  WorkspaceDxpWhatsappRoute: WorkspaceDxpWhatsappRoute,
  WorkspaceDxpIndexRoute: WorkspaceDxpIndexRoute,
}

const WorkspaceDxpRouteWithChildren = WorkspaceDxpRoute._addFileChildren(
  WorkspaceDxpRouteChildren,
)

interface WorkspaceRouteChildren {
  WorkspaceActivityRoute: typeof WorkspaceActivityRoute
  WorkspaceCalendarRoute: typeof WorkspaceCalendarRoute
  WorkspaceDxpRoute: typeof WorkspaceDxpRouteWithChildren
  WorkspaceLogisticsRoute: typeof WorkspaceLogisticsRoute
  WorkspacePmTasksRoute: typeof WorkspacePmTasksRoute
  WorkspacePrRoute: typeof WorkspacePrRoute
  WorkspaceSalesRoute: typeof WorkspaceSalesRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
  WorkspaceTasksRoute: typeof WorkspaceTasksRoute
  WorkspaceTeamRoute: typeof WorkspaceTeamRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceActivityRoute: WorkspaceActivityRoute,
  WorkspaceCalendarRoute: WorkspaceCalendarRoute,
  WorkspaceDxpRoute: WorkspaceDxpRouteWithChildren,
  WorkspaceLogisticsRoute: WorkspaceLogisticsRoute,
  WorkspacePmTasksRoute: WorkspacePmTasksRoute,
  WorkspacePrRoute: WorkspacePrRoute,
  WorkspaceSalesRoute: WorkspaceSalesRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
  WorkspaceTasksRoute: WorkspaceTasksRoute,
  WorkspaceTeamRoute: WorkspaceTeamRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SalesRoute: SalesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
